// Date: 08.02.2015 20:25:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package net.fexcraft.mod.frsm.blocks.kd;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class KD2Model extends ModelBase{
	
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape41;
    ModelRenderer Shape42;
    ModelRenderer Shape43;
    ModelRenderer Shape44;
    ModelRenderer Shape51;
    ModelRenderer Shape52;
    ModelRenderer Shape53;
    ModelRenderer Shape54;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
  
	public KD2Model(){
	    textureWidth = 64;
	    textureHeight = 32;
	    
	    Shape1 = new ModelRenderer(this, 0, 16);
	    Shape1.addBox(0F, 0F, 0F, 3, 0, 5);
	    Shape1.setRotationPoint(4F, 23.8F, -5F);
	    Shape1.setTextureSize(64, 32);
	    Shape1.mirror = true;
	    setRotation(Shape1, 0F, 0F, 0F);
	    Shape2 = new ModelRenderer(this, 0, 22);
	    Shape2.addBox(0F, 0F, 0F, 3, 4, 3);
	    Shape2.setRotationPoint(1F, 19.9F, 3F);
	    Shape2.setTextureSize(64, 32);
	    Shape2.mirror = true;
	    setRotation(Shape2, 0F, 0F, 0F);
	    Shape3 = new ModelRenderer(this, -7, 0);
	    Shape3.addBox(0F, 0F, 0F, 7, 0, 7);
	    Shape3.setRotationPoint(-6F, 23.9F, -6F);
	    Shape3.setTextureSize(64, 32);
	    Shape3.mirror = true;
	    setRotation(Shape3, 0F, 0F, 0F);
	    Shape41 = new ModelRenderer(this, 0, 11);
	    Shape41.addBox(0F, 0F, 0F, 1, 1, 3);
	    Shape41.setRotationPoint(0F, 22.9F, -4F);
	    Shape41.setTextureSize(64, 32);
	    Shape41.mirror = true;
	    setRotation(Shape41, 0F, 0F, 0F);
	    Shape42 = new ModelRenderer(this, 0, 11);
	    Shape42.addBox(0F, 0F, 0F, 1, 1, 3);
	    Shape42.setRotationPoint(-6F, 22.9F, -4F);
	    Shape42.setTextureSize(64, 32);
	    Shape42.mirror = true;
	    setRotation(Shape42, 0F, 0F, 0F);
	    Shape43 = new ModelRenderer(this, 0, 8);
	    Shape43.addBox(0F, 0F, 0F, 3, 1, 1);
	    Shape43.setRotationPoint(-4F, 22.9F, -6F);
	    Shape43.setTextureSize(64, 32);
	    Shape43.mirror = true;
	    setRotation(Shape43, 0F, 0F, 0F);
	    Shape44 = new ModelRenderer(this, 0, 8);
	    Shape44.addBox(0F, 0F, 0F, 3, 1, 1);
	    Shape44.setRotationPoint(-4F, 22.9F, 0F);
	    Shape44.setTextureSize(64, 32);
	    Shape44.mirror = true;
	    setRotation(Shape44, 0F, 0F, 0F);
	    Shape51 = new ModelRenderer(this, 0, 11);
	    Shape51.addBox(0F, 0F, 0F, 1, 1, 3);
	    Shape51.setRotationPoint(0.3F, 22.9F, -1.8F);
	    Shape51.setTextureSize(64, 32);
	    Shape51.mirror = true;
	    setRotation(Shape51, 0F, -0.7853982F, 0F);
	    Shape52 = new ModelRenderer(this, 0, 11);
	    Shape52.addBox(0F, 0F, 0F, 1, 1, 3);
	    Shape52.setRotationPoint(-3.9F, 22.9F, -6F);
	    Shape52.setTextureSize(64, 32);
	    Shape52.mirror = true;
	    setRotation(Shape52, 0F, -0.7853982F, 0F);
	    Shape53 = new ModelRenderer(this, 0, 11);
	    Shape53.addBox(0F, 0F, 0F, 1, 1, 3);
	    Shape53.setRotationPoint(1F, 22.9F, -3.9F);
	    Shape53.setTextureSize(64, 32);
	    Shape53.mirror = true;
	    setRotation(Shape53, 0F, -2.356194F, 0F);
	    Shape54 = new ModelRenderer(this, 0, 11);
	    Shape54.addBox(0F, 0F, 0F, 1, 1, 3);
	    Shape54.setRotationPoint(-3.2F, 22.9F, 0.3F);
	    Shape54.setTextureSize(64, 32);
	    Shape54.mirror = true;
	    setRotation(Shape54, 0F, -2.356194F, 0F);
	    Shape6 = new ModelRenderer(this, 9, 8);
	    Shape6.addBox(0F, 0F, 0F, 1, 1, 1);
	    Shape6.setRotationPoint(4F, 20F, 4F);
	    Shape6.setTextureSize(64, 32);
	    Shape6.mirror = true;
	    setRotation(Shape6, 0F, 0F, 0F);
	    Shape7 = new ModelRenderer(this, 9, 11);
	    Shape7.addBox(0F, 0F, 0F, 0, 3, 1);
	    Shape7.setRotationPoint(5F, 20F, 4F);
	    Shape7.setTextureSize(64, 32);
	    Shape7.mirror = true;
	    setRotation(Shape7, 0F, 0F, 0F);
	    Shape8 = new ModelRenderer(this, 10, 12);
	    Shape8.addBox(0F, 0F, 0F, 3, 0, 3);
	    Shape8.setRotationPoint(1F, 20.3F, 3F);
	    Shape8.setTextureSize(64, 32);
	    Shape8.mirror = true;
	    setRotation(Shape8, 0F, 0F, 0F);
    }
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5){
	    super.render(entity, f, f1, f2, f3, f4, f5);
	    setRotationAngles(f, f1, f2, f3, f4, f5);
	    Shape1.render(f5);
	    Shape2.render(f5);
	    Shape3.render(f5);
	    Shape41.render(f5);
	    Shape42.render(f5);
	    Shape43.render(f5);
	    Shape44.render(f5);
	    Shape51.render(f5);
	    Shape52.render(f5);
	    Shape53.render(f5);
	    Shape54.render(f5);
	    Shape6.render(f5);
	    Shape7.render(f5);
	    Shape8.render(f5);
	}
  
	private void setRotation(ModelRenderer model, float x, float y, float z){
	    model.rotateAngleX = x;
	    model.rotateAngleY = y;
	    model.rotateAngleZ = z;
	}
  
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5){
		super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
	}

}
